name: On PR Push - Build Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-checks:
    runs-on: [self-hosted, epoch-amd64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test Build Docker Image
        run: make check
