name: On PR Merge - Build & Push Multiarch

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-push-multiarch:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, epoch-amd64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & Push All
        run: |

          # Login for image push
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          make
